"""add amount column to payments

Revision ID: 06ca5d9f9835
Revises: aaa0898f989a
Create Date: 2025-11-19 12:49:32.136937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ca5d9f9835'
down_revision: Union[str, None] = 'aaa0898f989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
