"""add amount column to payments

Revision ID: 9f373ff35dcb
Revises: 06ca5d9f9835
Create Date: 2025-11-19 12:50:14.435374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f373ff35dcb'
down_revision: Union[str, None] = '06ca5d9f9835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
